### PR TITLE
fix: Add support for windows paths in checkstyle parser

### LINKED ISSUE #32: Handle windows paths in lint report
`<file name="C:\dev\lint-filter\src\parser.js">` should match against git diff which uses `src/parser.js`

### PR DESCRIPTION
**Pull request by relekang**
Fixes #32

### CODE REVIEW

File: src/parser.js [hunk 1]
```diff
@@ -5,8 +5,12 @@ import xml2js from 'xml2js'
 
 export const readFile = Promise.promisify(fs.readFile)
 
+export function makePathRelative(filepath) {
```
Comment (trygveaa) [inline src/parser.js]: Can't you use `path.relative` instead?

Comment (relekang) [inline src/parser.js]: I didn't get it to work right away. Will look more into it later.
